Adding server selection screen documentation
Rookout/docs pull request #366
Opened 2020-08-18 14:52 UTC by noagoldman

2020-08-19 06:44 UTC, ElDuderinos requested changes

2020-08-19 06:44 UTC, ElDuderinos commented on docs/server-selection.md
> +id: servers-selection
Maybe keep consistency with the filename?
"servers-selection" / "server-selection.md" ?

2020-08-19 06:44 UTC, ElDuderinos commented on docs/server-selection.md
> +2. One or set of filters that have been selected.
I think it should be "One or a set of filters that have been selected" or "One or the set of filters that have been selected".

2020-08-19 09:12 UTC, noagoldman commented on docs/server-selection.md
> +2. One or set of filters that have been selected.
Yep you are right

2020-08-19 09:23 UTC, noagoldman commented
/jira open task

2020-08-19 10:44 UTC, niryarden requested changes
Everything is only my opinion. and I'm far from being a docs expert (or an English writing expert). So consult further with @Rookeret73 / @yonitwis if you're not sure about anything I commented.

2020-08-19 10:44 UTC, niryarden commented on docs/server-selection.md
> +Choose instances that are running in a specific environment.
don't like the fact we're using `servers` and `instances` intermittently. shall we choose one term and stick to it?

2020-08-19 10:44 UTC, niryarden commented on docs/server-selection.md
> +Choose instances with a specific hostname, labels, process, IP, etc…
I think we should add `or` (or any similar word that sounds better) between the two sentences. otherwise, it sounds like they have to do both.

2020-08-19 10:44 UTC, niryarden commented on docs/server-selection.md
> +Filter your instances by [labels](projects-labels.md) that were defined during the Rookout SDK installation.
I'd consider saying `manually defined`, to emphasize it is their to decide 
Additionally, it's not really during the sdk **_installation_**, more like during the SDK **_setup_**.

2020-08-19 10:44 UTC, niryarden commented on docs/server-selection.md
> +
two things I think we should add:
1. A screenshot of the pencil in the top of the left pane. saying something like: 'click on the pencil to go to the server selection page and edit your debug session'. 
2. A paragraph about 'making your server selection page better' with an explanation that choose env is based on labels with env key (we must say it somewhere in the docs, here looks like a good place, and then i'll be able to reference to it in the docs link app itself). And also explain that the repo selection is based on the git_origin definition of your sdk setup, with a ref to the existing auto source fetching section in the docs.

2020-08-19 10:49 UTC, niryarden commented on docs/server-selection.md
> +
if you indeed add this paragraph, you can also mention in adding labels to your sdk setup. with a link to the labels page in the docs.
then, you'll be able to shorten the other filters paragraph without clearly distinguishing between labels and the rest of the filters, just saying something like `filter the servers using their labels, hostname, labels, process, IP, etc…`

2020-08-19 11:29 UTC, niryarden commented
also, we might want to completely delete the dynamic projects page. not only top remove it from the contents on the left pane.
so it won't be reachable by searching

2020-08-24 12:56 UTC, niryarden requested changes
hey, sorry if I'm giving you hard time with this PR :(
two general comments:
1. I think we should remove from this pr any reference to the server-selection name. it's a name we used for the design and development of the feature, and it's not relevant anymore. I believe future editors of the docs will be able to find the right spot, and that the uniformity we'll get by sticking to the costumer-facing name will make everything easier and prevent confusion.
2. I do believe that this page should include an explanation about the env dropdown and how it works, because I believe this is the place where users will look for it. That's my opinion - but it's your call.

2020-08-24 12:56 UTC, niryarden commented on docs/server-selection.md
> +To start a debug session, define at least one of the following filters:
not sure about the word 'define'. maybe 'select'?
because they're selecting from a list of options, not inventing filters from the head.
'select' is also the word we use in the UI.

2020-08-24 12:56 UTC, niryarden commented on docs/server-selection.md
> +Filter by a specific hostname, label, process, IP, etc…
`the Rookout SDK setup, or filter`
(add or, filter should not be capital case.)

2020-08-24 12:56 UTC, niryarden commented on docs/server-selection.md
> +chosen according to your filters. Click **Let's go** and start your debug session.
personally, i think `on the next debug session, according to the selected filters` is a bit clearer sentence.
and also maybe `Click let's go to start your debug session`.

both not a must

2020-08-24 12:56 UTC, niryarden commented on docs/server-selection.md
> +sidebar_label: Servers Selection
sidebar label is still server selection...

2020-08-24 12:56 UTC, niryarden commented on website/sidebars.json
> +      "server-selection",
debug session setup

2020-08-24 12:56 UTC, niryarden commented on docs/server-selection.md
> +Click on the pencil to **edit your debug session**.
maybe we should give some context?

`Later, while working inside your debug session, you can click the pencil any time to edit it again`.
wdyt?

2020-08-24 12:56 UTC, niryarden commented on docs/server-selection.md
> +1. Connected source code repositories.
we should reconsider that statement IMO.
the whole bookmarks feature changed, and just saying it saves connected sources is not very correct:
1. when you save a bookmark you can't even see what are your connected sources. it's transparent to you in this stage.
2. manually added sources aren't removed from the debug session if you switch bookmarks. they stay there until you manually remove them.
3. auto-added sources would be auto-fetched following the bookmark filters loading anyway, so the fact that the bookmark saves them is practically pointless.

In general, I think we can consider deprecating the bookmark feature or rethink the way it works.
but specifically regarding this PR - I wouldn't mention the sources. I would rephrase this whole paragraph, explaining that bookmarks are made for naming different debug session setups, by saving sets of selected filters.

2020-08-24 13:04 UTC, noagoldman commented on docs/server-selection.md
> +Click on the pencil to **edit your debug session**.
How about: Click on the pencil from your / the current debug session to edit and change instances?

2020-08-24 13:05 UTC, niryarden commented on docs/server-selection.md
> +Click on the pencil to **edit your debug session**.
yeah whatever sounds good to you.
just wanted it to be in the context of being inside a debug session

2020-08-24 13:07 UTC, noagoldman commented on docs/server-selection.md
> +1. Connected source code repositories.
I don't think we want to deprecate the bookmark feature, users use it a lot. I will remove it from this page though :)

2020-08-24 13:07 UTC, noagoldman commented on docs/server-selection.md
> +Click on the pencil to **edit your debug session**.
Understood

2020-08-24 13:10 UTC, niryarden commented on docs/server-selection.md
> +1. Connected source code repositories.
the comment about deprecating is just a thought i had, but i agree we should think about it further.

regarding the docs - i wouldn't remove it completely, because this is where users will look for an answer when they'll see it in the server selection page and won't understand what it is.
I do think we should mention it, but I think we should not mention source repos are involved

2020-08-24 13:33 UTC, niryarden approved these changes

2020-08-24 13:36 UTC, merged