Imrproving the dotnet copy
Rookout/docs pull request #396
Opened 2020-12-16 11:27 UTC by LiranLast

2020-12-16 11:28 UTC, LiranLast commented
/jira open task

2020-12-16 15:54 UTC, ElDuderinos requested changes

2020-12-16 15:54 UTC, ElDuderinos commented on docs/dotnet-setup.md
> +Rookout requires your application to be built and deployed with a debug information in the form of a pdb file. Rookout supports the `full`, `portable` and `pdbonly` configurations, while `embedded` i
You removed the instructions on how to do this:
`<DebugType>full/portable/pdbonly</DebugType>`
If this is needed then we don't expect the customer to start googling how to do that...

2020-12-16 16:01 UTC, LiranLast commented on docs/dotnet-setup.md
> +Rookout requires your application to be built and deployed with a debug information in the form of a pdb file. Rookout supports the `full`, `portable` and `pdbonly` configurations, while `embedded` i
That was hardly instructions :)

Where in the file does it go? Is it per project? Per solution? Something else? :)

2020-12-16 16:27 UTC, ElDuderinos commented on docs/dotnet-setup.md
> +Rookout requires your application to be built and deployed with a debug information in the form of a pdb file. Rookout supports the `full`, `portable` and `pdbonly` configurations, while `embedded` i
The same place where you place the Optimize, MSBuildGitHashCommand and EmbedAllSources parameters. Per project's PropertyGroup.

2020-12-16 16:35 UTC, LiranLast commented on docs/dotnet-setup.md
> +Rookout requires your application to be built and deployed with a debug information in the form of a pdb file. Rookout supports the `full`, `portable` and `pdbonly` configurations, while `embedded` i
That's not documented anywhere...

Want to suggest some copy? Maybe in a new section?

2020-12-20 13:42 UTC, LiranLast commented on docs/dotnet-setup.md
> +Rookout requires your application to be built and deployed with a debug information in the form of a pdb file. Rookout supports the `full`, `portable` and `pdbonly` configurations, while `embedded` i
@ElDuderinos can we merge?

2020-12-22 13:12 UTC, LiranLast commented
@ElDuderinos let's merge this :)

2020-12-22 17:05 UTC, ElDuderinos approved these changes

2020-12-22 17:05 UTC, merged