Update dotnet-setup.md
Rookout/docs pull request #430
Opened 2021-06-10 11:52 UTC by ElinorSwery

2021-06-10 11:52 UTC, ElinorSwery commented
/jira create bug

2021-06-10 11:52 UTC, ElinorSwery commented
/jira open bug

2021-06-10 11:59 UTC, lirook approved these changes

2021-06-14 06:23 UTC, ElDuderinos requested changes

2021-06-14 06:23 UTC, ElDuderinos commented on docs/dotnet-setup.md
> +Start the SDK within your application, by adding the following to your *main* method:
*main* isn't always the right answer.
This should be "*main* method or your application's entry point".

2021-06-20 05:41 UTC, ElDuderinos approved these changes

2021-06-20 05:41 UTC, merged