Git and Powershell are not needed
Rookout/docs pull request #431
Opened 2021-06-13 12:52 UTC by lirook

2021-06-13 12:53 UTC, lirook commented
/jira open task

2021-06-14 06:25 UTC, ElDuderinos requested changes
We need git installed in order for this to work - https://github.com/Rookout/docs/blob/master/docs/dotnet-setup.md#source-information
So maybe at least write something about Git over there?

2021-06-20 12:53 UTC, lirook commented
@ElDuderinos 
Look at the changes I just added :) tell me if you like it better

2021-06-20 17:52 UTC, ElDuderinos approved these changes

2021-07-04 04:36 UTC, merged