Update supported node versions
Rookout/docs pull request #458
Opened 2021-08-18 11:36 UTC by lirook

2021-09-12 08:53 UTC, lirook commented
@ElDuderinos what do you think?

2021-09-15 06:15 UTC, ElDuderinos requested changes

2021-09-15 06:15 UTC, ElDuderinos commented on docs/node-setup.md
> +| **14**   | 14.0.0 --> 14.17.5 |
We also added 14.17.6

2021-09-15 06:15 UTC, ElDuderinos commented on docs/node-setup.md
> +| **14**   | 13.0.0 --> 13.14.0 |
There's some mess here with the release part.
Also, why do you need to detail the minor/patch versions? (apart for <=12.4)

2021-09-19 06:29 UTC, lirook commented on docs/node-setup.md
> +| **14**   | 13.0.0 --> 13.14.0 |
Yep, fixing the mess.
As for the patch versions, I did it for consistency

2021-10-18 11:58 UTC, ElDuderinos submitted a review, later dismissed

2021-11-01 11:46 UTC, ElDuderinos approved these changes

2021-11-01 11:47 UTC, ElDuderinos commented
/jira open task

2021-11-01 11:47 UTC, merged