Remove repository settings section
Rookout/docs pull request #487
Opened 2021-11-28 09:49 UTC by lirook

2021-11-28 09:52 UTC, lirook commented
/jira open task

2021-11-28 09:53 UTC, lirook commented
@eladuzan94 @ElinorSwery @jhendrick
FYI

2021-11-29 09:22 UTC, LiranLast commented on docs/source-repos.md
> -### (Node) Debugging Packages
@lirook this might still needed - we don't have a browser-based workaround for it

2021-11-29 21:22 UTC, jhendrick commented
> @eladuzan94 @ElinorSwery @jhendrick FYI

Dudi and I actually had to use this .rookout file approach a few weeks ago for a source mismatch issue on a POC call

2021-11-30 08:40 UTC, lirook commented on docs/source-repos.md
> -### (Node) Debugging Packages
I'll add it to the node setup page

2021-11-30 08:49 UTC, LiranLast commented on docs/source-repos.md
> -### (Node) Debugging Packages
I'm not sure it belongs there.

We might want to try making smaller changes first? :)

2021-11-30 08:51 UTC, lirook commented
> > @eladuzan94 @ElinorSwery @jhendrick FYI
> 
> Dudi and I actually had to use this .rookout file approach a few weeks ago for a source mismatch issue on a POC call

It's good that we have that workaround when needed, but I think it shouldn't be in the customer-facing docs. WDYT @jhendrick?

2021-11-30 09:34 UTC, lirook commented on docs/node-setup.md
> +### Debugging Node Modules
@LiranLast
In my opinion, this fits well here. Do you not agree? :)

2021-12-02 04:54 UTC, jhendrick commented
> > @eladuzan94 @ElinorSwery @jhendrick FYI
> 
> Dudi and I actually had to use this .rookout file approach a few weeks ago for a source mismatch issue on a POC call

Yea that's fair. It's rarely used now so as long as we have it saved that should be good.

2021-12-14 07:09 UTC, ElDuderinos requested changes

2021-12-14 07:09 UTC, ElDuderinos commented on docs/node-setup.md
> +```
The file needs to be named ".rookout"

2021-12-14 11:15 UTC, lirook commented on docs/node-setup.md
> +```
Oops. Adding it

2021-12-19 05:51 UTC, ElDuderinos approved these changes

2021-12-19 05:52 UTC, merged