Node SDK Docs Improvements
Rookout/docs pull request #488
Opened 2021-11-29 08:28 UTC by lirook

Deleted obselete sections
Improved source mapping section
Overall fixes and improvements

2021-11-29 08:29 UTC, lirook commented
/jira open task

2021-11-29 08:32 UTC, lirook commented
@jhendrick @ElinorSwery @eladuzan94 
FYI

2021-11-29 09:00 UTC, LiranLast commented on docs/node-setup.md
> -This page will dive into the nitty gritty details on installing Rookout under various configurations.
Why delete this? :)

2021-11-29 09:00 UTC, LiranLast commented on docs/node-setup.md
> -The [NodeJS SDK](https://www.npmjs.com/package/rookout) provides the ability to fetch debug data from a running application in real time.
Why delete the link? :)

2021-11-29 09:01 UTC, LiranLast commented on docs/node-setup.md
> +**Yarn**
Let's use multi-lang blocks if we want to offer multiple package managers

2021-11-29 09:02 UTC, LiranLast commented on docs/node-setup.md
> +Note that the `rookout.start` method returns a promise that resolves when the connection attempt succeeds or fails. You can choose to utilize that Promise or to ignore it.
Need to explain when that promise is resolved and/or rejected :)

2021-11-29 09:02 UTC, LiranLast commented on docs/node-setup.md
> +| `throw_errors` | --- | False | Set to `True` to reject the promsise or throw an exception if `start` fails (error messages are not printed to the console when this is set) |
This description is very inaccurate :)

2021-11-29 09:03 UTC, LiranLast commented on docs/node-setup.md
>  | `token` | `ROOKOUT_TOKEN` | None | The Rookout token for your organization. Should be left empty if you are using a Rookout ETL Controller |
Should => May

2021-11-29 09:03 UTC, LiranLast commented on docs/node-setup.md
> -flush(cb);
Flush is important for some Serverless use-cases. Are we sure we want to remove it?

2021-11-29 09:04 UTC, LiranLast commented on docs/node-setup.md
> -## Test connectivity
These are useful sections for troubleshooting. Are we sure we want to remove them?

2021-11-29 14:21 UTC, lirook commented on docs/node-setup.md
> -This page will dive into the nitty gritty details on installing Rookout under various configurations.
Because it felt a little obvious and casual. Do you think I should not remove it anyway? :)

2021-11-29 14:59 UTC, LiranLast commented on docs/node-setup.md
> -This page will dive into the nitty gritty details on installing Rookout under various configurations.
I like casual :)

2021-11-29 15:23 UTC, lirook commented on docs/node-setup.md
> -## Test connectivity
Which sections? Connectivity Test? or others as well? (I'm not sure we should keep the connectivity test)

2021-11-29 15:28 UTC, lirook commented on docs/node-setup.md
> -This page will dive into the nitty gritty details on installing Rookout under various configurations.
I'll re add it

2022-01-02 06:42 UTC, ElDuderinos commented on docs/node-setup.md
> +Note that the `rookout.start` method returns a promise that resolves when the connection attempt succeeds or fails. You can choose to utilize that Promise or to ignore it.
@lirook 
Promise is resolved upon successful initialization of the agent or in case it was already initialized. 
If throw_errors is set to false (default) then the promise is also resolved on failure to initialize.
If throw_errors is set to true then the promise is rejected upon failure to initialize.

2022-01-02 06:50 UTC, ElDuderinos requested changes

2022-01-02 06:50 UTC, ElDuderinos commented on docs/node-setup.md
> +| `throw_errors` | --- | False | Set to `True` to reject the promsise or throw an exception if `start` fails (error messages are not printed to the console when this is set) |
@lirook
See the explanation I wrote (https://github.com/Rookout/docs/pull/488#discussion_r777172179)
Also, change "promsise" to "promise"

2022-01-02 06:50 UTC, ElDuderinos commented on docs/node-setup.md
> -```
We can't remove this, this is important.
Where would a user see this explanation elsewhere?

2022-01-02 06:50 UTC, ElDuderinos commented on docs/node-setup.md
> -## Test connectivity
What's wrong with the connectivity test? We should use it more with customers experiencing self service trouble.

2022-01-02 06:50 UTC, ElDuderinos commented on docs/node-setup.md
> +### Advanced transpiling configurations
The instructions below are specific to Webpack, why change the title?

2022-01-02 06:50 UTC, ElDuderinos commented on docs/node-setup.md
> -
Why remove this?

2022-01-02 06:50 UTC, ElDuderinos commented on docs/node-setup.md
> +For most serverless types, Rookout can be installed as usual.
"as usual" ? Let's think about something more technical/professional.

2022-01-02 14:09 UTC, lirook commented on docs/node-setup.md
> -## Test connectivity
well, it only works with environment variables. I can see how it may really confuse some users who use config arguments. Also, we rarely have cases where we need to troubleshoot the connection and use the connectivity test.

If you're not convinced, I'll re-add it.

2022-01-03 14:47 UTC, lirook commented on docs/node-setup.md
> -```
Okay

2022-01-03 14:50 UTC, lirook commented on docs/node-setup.md
> +### Advanced transpiling configurations
Because they are specific to TS + WP, not just WP, and we may add more types of advanced configurations here

2022-01-03 15:18 UTC, lirook commented on docs/node-setup.md
> +Note that the `rookout.start` method returns a promise that resolves (fulfills) when the connection attempt either succeeds or fails. You can change this behavior by setting the `throw_errors` parame
@ElDuderinos is this accurate?

2022-01-03 15:18 UTC, lirook commented on docs/node-setup.md
> +| `throw_errors` | --- | False | Set to `True` to reject the promsie when `start` fails |
@ElDuderinos how's that?

2022-01-09 19:05 UTC, ElDuderinos approved these changes

2022-01-11 15:54 UTC, merged