Datastore docs and Controller docs improvements
Rookout/docs pull request #489
Opened 2021-12-01 17:09 UTC by lirook

Created documentation for the Datastore
Improved the documentation for the ETL controller
Changed the color of code snippets in the docs

2021-12-01 17:10 UTC, lirook commented
/jira open story

2021-12-02 09:36 UTC, LiranLast commented on docs/dop-config.md
> +id: dop-config
Let's use datastore-config? :)

2021-12-02 09:37 UTC, LiranLast commented on docs/etl-controller-install.md
> +To install the Controller as a Docker container (using [this image](https://hub.docker.com/r/rookout/controller/)), execute the following:
`To deploy`

2021-12-02 11:10 UTC, lirook commented on docs/dop-config.md
> +id: dop-config
It's just the URL, the title and the side bar is "datastore".
I called it dop because it's under the "Data On-Premise" section :)

2021-12-02 11:11 UTC, lirook commented on docs/etl-controller-install.md
> +To install the Controller as a Docker container (using [this image](https://hub.docker.com/r/rookout/controller/)), execute the following:
Agreed

2022-03-10 11:47 UTC, ElDuderinos requested changes

2022-03-10 11:47 UTC, ElDuderinos commented on docs/etl-controller-config.md
> +For security best practices, you should set this to `false` unless the connection is trusted and secure.
shouldn't it be "you shouldn't" ?

2022-03-10 11:47 UTC, ElDuderinos commented on docs/etl-controller-intro.md
> +The SDK instances connect to the Controller over WebSocket through port 7488 by default. The Controller's hostname needs to be configured for each SDK instance.
An SDK agent always uses port 443 by default unless set by ROOKOUT_CONTROLLER_PORT

2022-03-10 12:27 UTC, lirook commented on docs/etl-controller-config.md
> +For security best practices, you should set this to `false` unless the connection is trusted and secure.
no :)

2022-03-10 12:32 UTC, lirook commented on docs/etl-controller-intro.md
> +The SDK instances connect to the Controller over WebSocket through port 7488 by default. The Controller's hostname needs to be configured for each SDK instance.
fixed it

2022-03-23 07:30 UTC, ElDuderinos approved these changes

2022-03-23 07:30 UTC, merged