Improve Breakpoints Docs
Rookout/docs pull request #495
Opened 2021-12-27 12:08 UTC by lirook

2021-12-27 15:46 UTC, lirook commented
/jira open task

2021-12-30 08:28 UTC, lirook commented
@eladuzan94 @jhendrick @ElinorSwery FYI

2021-12-30 13:03 UTC, lirook commented on docs/breakpoint-limits.md
> +---
On this page, I only removed a couple of things such as the JSON reference, I didn't yet go over it and fix stuff.
This page needs a lot more work...

2022-02-17 05:34 UTC, ElDuderinos requested changes

2022-02-17 05:34 UTC, ElDuderinos commented on docs/breakpoint-limits.md
> +As a matter of safety to your application, when a single breakpoint run takes more than a reasonable time to run, it is disabled permanently. When this happens, the breakpoint will need to be manuall
This is the same as "Maximum execution time limit", you can remove one of them

2022-02-17 05:34 UTC, ElDuderinos commented on docs/breakpoint-limits.md
> +This is a soft limit - once it is hit, the breakpoint will be disabled but it may take a short while for it to be received and handled by your app instances, so you may see more hits than your limit.
Why not add also the time limit?

2022-02-17 05:34 UTC, ElDuderinos commented on docs/breakpoints.md
> +- Hit count (the number of times the breakpoint gets triggered)
You wrote about the hit count in breakpoint-limits.md
Either choose one place or properly reference from here to there.

2022-02-17 10:04 UTC, ElDuderinos approved these changes

2022-02-17 12:15 UTC, merged