changes to transpilling docs
Rookout/docs pull request #509
Opened 2022-02-15 16:34 UTC by GuyGazit

2022-02-15 16:34 UTC, GuyGazit commented
/jira open task minor

2022-02-22 09:12 UTC, lirook requested changes
I left some suggested changes. Let me know what you think

2022-02-22 09:13 UTC, LiranLast commented on docs/node-setup.md
> +Packing Rookout and other dependencies in general might create unnecessary issues, so we should leave them unpacked.
This statement is false :(

`and other dependencies in general might create unnecessary issues`

2022-02-22 09:13 UTC, LiranLast commented on docs/node-setup.md
> +IMPORTANT: Don't forget to copy your `node_modules` directory to your server cause it is no longer packed.
This comment is not applicable to Serverless application which is where we are seeing the most use of Webpack...

2022-02-22 09:34 UTC, LiranLast commented on docs/node-setup.md
> +### Don't Pack Rookout
Let's make it softer?

We don't recommend it? Setting up Webpack to pack Rookout can get tricky?

2022-02-22 10:20 UTC, lirook commented on docs/node-setup.md
> +Packing Rookout and other dependencies in general might create unnecessary issues, so we should leave them unpacked.
Which statement? @LiranLast Guy's, or my suggestion?

2022-02-22 10:25 UTC, lirook commented on docs/node-setup.md
> +IMPORTANT: Don't forget to copy your `node_modules` directory to your server cause it is no longer packed.
@LiranLast it looks [here](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-package.html#nodejs-package-dependencies) like it is applicable, but I will make sure to also add documentation about our Lambda layer under the serverless section. WDYT?

2022-02-22 10:27 UTC, LiranLast commented on docs/node-setup.md
> +Packing Rookout and other dependencies in general might create unnecessary issues, so we should leave them unpacked.
That packaging deps is unnecessary :)

2022-02-22 10:30 UTC, lirook commented on docs/node-setup.md
> +IMPORTANT: Don't forget to copy your `node_modules` directory to your server cause it is no longer packed.
Guy suggested to use `nodeExternals()` though, doesn't that mean we need everything from `node_modules`?

2022-02-22 10:31 UTC, lirook commented on docs/node-setup.md
> +Packing Rookout and other dependencies in general might create unnecessary issues, so we should leave them unpacked.
Cool, so let's go with my copy :)

2022-02-22 10:32 UTC, LiranLast commented on docs/node-setup.md
> +IMPORTANT: Don't forget to copy your `node_modules` directory to your server cause it is no longer packed.
If that's why they choose to do.

We should probably also show how to exclude just Rookout (as Datadog does) as I believe at least some of customers will prefer not to do that.

2022-02-22 10:33 UTC, lirook commented on docs/node-setup.md
> +IMPORTANT: Don't forget to copy your `node_modules` directory to your server cause it is no longer packed.
I agree, testing locally I was able to do so with:
```javascript
  externals: {
    rookout: 'commonjs rookout'
  }
```

2022-02-22 10:34 UTC, LiranLast commented on docs/node-setup.md
> +Packing Rookout and other dependencies in general might create unnecessary issues, so we should leave them unpacked.
How about:

By default, Webpack will pack Rookout together with all other JS packages. Setting up packaging for the Rookout package can get tricky, and so we recommend excluding it by following these instructions:

2022-02-28 11:16 UTC, lirook approved these changes

2022-03-03 12:05 UTC, merged