RK-14345 node serverless tutorial
Rookout/docs pull request #622
Opened 2022-10-12 06:36 UTC by hopemanryan

https://rookout.atlassian.net/browse/RK-14345

2022-10-12 11:43 UTC, lirook requested changes

2022-10-12 11:43 UTC, lirook commented on docs/node-serverless-tutorial.mdx
> +title: "Deploy Rookout on a Node.JS with 'Serverless-Framework' "
```suggestion
title: "Deploy Rookout on a Node.JS with 'Serverless-Framework'"
```

2022-10-12 11:43 UTC, lirook commented on docs/node-serverless-tutorial.mdx
> +git clonehttps://github.com/Rookout/tutorial-nodejs-serverless-2022
```suggestion
git clone https://github.com/Rookout/tutorial-nodejs-serverless-2022
```

2022-10-12 11:43 UTC, lirook commented on docs/node-serverless-tutorial.mdx
> +git clonehttps://github.com/Rookout/tutorial-nodejs-serverless-2022
```suggestion
git clone https://github.com/Rookout/tutorial-nodejs-serverless-2022
```

2022-10-12 11:43 UTC, lirook commented on docs/node-serverless-tutorial.mdx
> +### 1. Add the Rookout npm Package
```suggestion
### 1. Add the Rookout SDK
```

2022-10-12 11:43 UTC, lirook commented on docs/node-serverless-tutorial.mdx
> +Rookout for NodeJS is a simple npm Package.
```suggestion
The Rookout SDK for NodeJS is a simple node module that allows you to run the Rookout agent.
```

2022-10-12 11:43 UTC, lirook commented on docs/node-serverless-tutorial.mdx
> +Load and start the package to connect to your Rookout account (if you haven't signed up, do that [here](https://app.rookout.com/#mode=signUp)).
```suggestion
Load the Rookout module and configure the agent with your Rookout account token (if you haven't signed up yet, you can do that [here](https://app.rookout.com/#mode=signUp)).
```

2022-10-12 11:43 UTC, lirook commented on docs/node-serverless-tutorial.mdx
> +The start function returns a promise - wait for it to debug the application initialization code.
What do you mean by "debug the application initialization code"?

2022-10-12 11:43 UTC, lirook commented on docs/node-serverless-tutorial.mdx
> +### 4. Deploying to s3 and communicate with our serverless functions
```suggestion
### 4. Deploying to S3
```

2022-10-12 11:43 UTC, lirook commented on docs/node-serverless-tutorial.mdx
> +After deployment has been successful we can access it through [https://[bucket-name].s3.amazonaws.com/index.html](https://[bucket-name].s3.amazonaws.com/index.html)
```suggestion
After a successful deployment we can access our function through [https://[bucket-name].s3.amazonaws.com/index.html](https://[bucket-name].s3.amazonaws.com/index.html)
```

2022-10-12 12:03 UTC, LiranLast commented on docs/node-serverless-tutorial.mdx
> +### 3. Deploy your serverless application
This step should have two "versions":
1. One for SLS in general
2. One for our extra work regarding S3

2022-10-12 12:03 UTC, LiranLast commented on docs/node-serverless-tutorial.mdx
> +### 4. Deploying to s3 and communicate with our serverless functions
No step 4

2022-10-12 12:03 UTC, LiranLast commented on docs/node-serverless-tutorial.mdx
> +### Questions?
What about auto-source fetching?

2022-10-12 12:05 UTC, LiranLast commented on docs/node-serverless-tutorial.mdx
> +npm install
Is this needed?

2022-10-12 14:29 UTC, LiranLast commented on docs/node-serverless-tutorial.mdx
> +Rookout for NodeJS is a simple npm Package.
Short is better then long :)

2022-10-13 05:44 UTC, hopemanryan commented on docs/node-serverless-tutorial.mdx
> +title: "Deploy Rookout on a Node.JS with 'Serverless-Framework' "
done

2022-10-13 05:46 UTC, hopemanryan commented on docs/node-serverless-tutorial.mdx
> +npm install
changed

2022-10-13 05:47 UTC, hopemanryan commented on docs/node-serverless-tutorial.mdx
> +The start function returns a promise - wait for it to debug the application initialization code.
not relevant , copied from other

2022-10-13 05:48 UTC, hopemanryan commented on docs/node-serverless-tutorial.mdx
> +### Questions?
What about it ?

2022-10-13 10:21 UTC, lirook commented on docs/node-serverless-tutorial.mdx
> +Rookout for NodeJS is a simple npm Package.
"The Rookout SDK for NodeJS is a simple node module." is also fine :)

2022-10-16 08:41 UTC, Urook commented on docs/node-serverless-tutorial.mdx
> +### Questions?
Either the .git dir or the git url + commit need to be defined for auto fetching to work

2022-11-23 19:23 UTC, LiranLast commented
@naomirookout

2022-12-21 06:43 UTC, Urook requested changes

2022-12-21 06:43 UTC, Urook commented on docs/node-serverless-tutorial.mdx
> +To add UI which interacts with those endpoints. Copy the endpoint printed `https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com` and go to `static/js/app.js` replace all instances of `[lambda_endpo
@naomirookout I just had an idea. You could add an env var for lambda endpoint and use it in the app, instead of having the users change it in the code.

2023-02-15 15:30 UTC, closed without merging