New hybrid deployments page
Rookout/docs pull request #657
Opened 2023-02-05 17:10 UTC by naomirookout

2023-02-05 17:10 UTC, naomirookout commented
Still need to remove the ETL controller and datastore pages (replacing references to them with new references to this page)

2023-02-07 19:36 UTC, LiranLast commented on docs/hybrid-deployments.mdx
> +Rookout's hybrid SaaS architecture empowers customers to keep all application data within their premise by separating the control plane from the data plane.
Let's remove `all` :)

2023-02-07 19:36 UTC, LiranLast commented on docs/hybrid-deployments.mdx
> +Keeping the control plane connected to the Rookout cloud retains all the benefits of SaaS: ease of use, ease of maintenance, live updates, etc.
Again, let's remove all :)

2023-02-07 19:37 UTC, LiranLast commented on docs/hybrid-deployments.mdx
> +Otherwise, agents will connect to the Rookout cloud, but every breakpoint will result in the following error message:
How about:

If you forget to set the Rookout controller host, every breakpoint...

2023-02-07 19:38 UTC, LiranLast commented on docs/hybrid-deployments.mdx
> +[//]: # (todo add the error message / a screen shot after improving the error's copy)
Let's finish this :)

2023-02-08 14:41 UTC, naomirookout commented
/jira open task

2023-02-08 15:10 UTC, LiranLast submitted a review, later dismissed

2023-02-08 18:24 UTC, Urook commented on docs/etl-controller-config.md
> -| [Rookout token](#rookout-token)                                     | `ROOKOUT_TOKEN`                  | Rookout token                   | -              |
@naomirookout Is there another place where all those env vars are detailed?

2023-02-08 18:26 UTC, LiranLast commented on docs/etl-controller-config.md
> -| [Rookout token](#rookout-token)                                     | `ROOKOUT_TOKEN`                  | Rookout token                   | -              |
@naomirookout let's leave those pages existing but not accessible for now...

2023-02-13 06:42 UTC, Urook requested changes

2023-02-13 06:42 UTC, Urook commented on docs/dotnet-container-tutorial.md
> +2.  If you are using [Rookout's hybrid architecture](hybrid-deployments.mdx), set up the controller host.
Why is this one different than the other container tutorials?

2023-02-13 06:49 UTC, Urook commented on docs/hybrid-deployments.mdx
> +        {label: 'Environment Variable / JVM', value: 'env'},
This can be used with node too (when using the -r node cli flag

2023-02-13 07:38 UTC, LiranLast commented on docs/hybrid-deployments.mdx
> +        {label: 'Environment Variable / JVM', value: 'env'},
@naomirookout I was sure we discussed have both `Environment Variable` and `JVM`

2023-02-13 07:39 UTC, LiranLast commented on docs/hybrid-deployments.mdx
> +If you forget to set the Rookout controller host you will be unable to set a breakpoint, and you'll see the following error: "Agent attempted connection to SaaS."
`unable to set breakpoints` - no?

Is the `and` necessary?

2023-02-13 09:15 UTC, LiranLast commented on docs/dotnet-container-tutorial.md
> +2.  If you are using [Rookout's hybrid architecture](hybrid-deployments.mdx), set up the controller host.
@Urook please don't request changes on a PR you don't own the code for :)

2023-02-13 17:52 UTC, LiranLast commented on docs/hybrid-deployments.mdx
> +        {label: 'Environment Variable', value: 'env'}
Let's make it first? :)

2023-02-13 17:53 UTC, LiranLast commented on docs/hybrid-deployments.mdx
> +export JAVA_TOOL_OPTIONS="-javaagent:$(pwd)/rook.jar -DROOKOUT_TOKEN=[Your Rookout Token] -DROOKOUT_CONTROLLER_HOST="wss://your-controller-host"
Looks buggy in "

2023-02-13 17:59 UTC, naomirookout commented on docs/hybrid-deployments.mdx
> +export JAVA_TOOL_OPTIONS="-javaagent:$(pwd)/rook.jar -DROOKOUT_TOKEN=[Your Rookout Token] -DROOKOUT_CONTROLLER_HOST="wss://your-controller-host"
This is what it will look like - 
![image](https://user-images.githubusercontent.com/109460664/218536164-5ac45013-d7af-42ff-ad53-6b6d0422e755.png)

2023-02-13 17:59 UTC, naomirookout commented on docs/hybrid-deployments.mdx
> +export JAVA_TOOL_OPTIONS="-javaagent:$(pwd)/rook.jar -DROOKOUT_TOKEN=[Your Rookout Token] -DROOKOUT_CONTROLLER_HOST="wss://your-controller-host"
![image](https://user-images.githubusercontent.com/109460664/218536219-27cf2f50-aac0-401a-82d6-aa8810fceebf.png)

2023-02-13 19:04 UTC, LiranLast approved these changes

2023-02-13 20:24 UTC, naomirookout commented
@Urook please approve :)

2023-02-13 20:37 UTC, Urook approved these changes

2023-02-13 20:37 UTC, merged